config/routes.rb
# This file contains configuration for Danbooru's URL routes. It defines all the
# URL endpoints and HTTP redirects used by Danbooru.
#
# A list of routes can be found at http://localhost:3000/rails/info/routes when
# running the server in development mode. You can also run `bin/rails routes` to
# produce a list of routes.
#
# @see https://guides.rubyonrails.org/routing.html
# @see http://localhost:3000/rails/info/routes
Rails.application.routes.draw do
  resources :posts, only: [:index, :show, :update, :destroy] do
    get :random, on: :collection
  end

  resources :autocomplete, only: [:index]

  # XXX This comes *after* defining posts above because otherwise the paginator
  # generates `/?page=2` instead of `/posts?page=2` on the posts#index page.
  root "posts#index"

  namespace :admin do
    resources :users, :only => [:edit, :update]
  end
  namespace :moderator do
    resource :dashboard, :only => [:show]
    resources :ip_addrs, :only => [:index] do
      collection do
        get :search
      end
    end
    namespace :post do
      resources :posts, :only => [:delete, :expunge, :confirm_delete] do
        member do
          post :expunge
          get :confirm_move_favorites
          post :move_favorites
          post :ban
          post :unban
        end
      end
    end
    resources :ip_addrs, :only => [:index, :search] do
      collection do
        get :search
      end
    end
  end
  namespace :explore do
    resources :posts, :only => [] do
      collection do
        get :popular
        get :curated
        get :viewed
        get :searches
        get :missed_searches
      end
    end
  end
  namespace :maintenance do
    namespace :user do
      resource :count_fixes, only: [:new, :create]
      resource :email_notification, :only => [:show, :destroy]
      resource :deletion, :only => [:show, :destroy]
    end
  end

  resources :api_keys, only: [:new, :create, :edit, :update, :index, :destroy]

  resources :artists do
    member do
      put :revert
      put :ban
      put :unban
    end
    collection do
      get :show_or_new
      get :banned
    end
  end
  resources :artist_urls, only: [:index]
  resources :artist_versions, :only => [:index, :show] do
    collection do
      get :search
    end
  end
  resources :bans
  resources :bulk_update_requests do
    member do
      post :approve
    end
  end
  resources :comment_votes, only: [:index, :show, :destroy]
  resources :comments do
    resource :votes, controller: "comment_votes", only: [:create, :destroy], as: "comment_votes" do
      get "/", action: :index
    end
    collection do
      get :search
    end
    member do
      post :undelete
    end
  end
  resources :counts do
    collection do
      get :posts
    end
  end
  resources :delayed_jobs, :only => [:index, :destroy] do
    member do
      put :run
      put :retry
      put :cancel
    end
  end
  resources :dmails, :only => [:new, :create, :update, :index, :show] do
    collection do
      post :mark_all_as_read
    end
  end
  resource  :dtext_preview, :only => [:create]
  resources :dtext_links, only: [:index]
  resources :emails, only: [:index, :show]
  resources :favorites, :only => [:index, :create, :destroy]
  resources :favorite_groups do
    member do
      put :add_post
    end
    resource :order, :only => [:edit], :controller => "favorite_group_orders"
  end
  resources :forum_posts do
    member do
      post :undelete
    end
    collection do
      get :search
    end
  end
  resources :forum_post_votes, only: [:index, :show, :create, :destroy]
  resources :forum_topics do
    member do
      post :undelete
    end
    collection do
      post :mark_all_as_read
    end
  end
  resources :forum_topic_visits, only: [:index]
  resources :ip_bans, only: [:index, :new, :create, :update]
  resources :ip_addresses, only: [:show, :index], id: /.+?(?=\.json|\.xml|\.html)|.+/
  resources :ip_geolocations, only: [:index]
  resource :iqdb_queries, :only => [:show, :create] do
    collection do
      get :preview
      get :check, to: redirect {|path_params, req| "/iqdb_queries?#{req.query_string}"}
    end
  end
  resources :media_assets, only: [:index, :show]
  resources :media_metadata, only: [:index]
  resources :mod_actions
  resources :moderation_reports, only: [:new, :create, :index, :show]
  resources :modqueue, only: [:index]
  resources :news_updates
  resources :notes do
    member do
      put :revert
    end
  end
  resources :note_versions, :only => [:index, :show]
  resource :note_previews, :only => [:show]
  resource :password_reset, only: [:create, :show]
  resources :pixiv_ugoira_frame_data, only: [:index]
  resources :pools do
    member do
      put :revert
      post :undelete
    end
    collection do
      get :gallery
    end
    resource :order, :only => [:edit], :controller => "pool_orders"
  end
  resource :pool_element, :only => [:create]
  resources :pool_versions, :only => [:index] do
    member do
      get :diff
    end
    collection do
      get :search
    end
  end
  resources :post_regenerations, :only => [:create]
  resources :post_replacements, :only => [:index, :new, :create, :update]
  resources :post_votes, only: [:index, :show, :create, :destroy]

  # XXX Use `only: []` to avoid redefining post routes defined at top of file.
  resources :posts, only: [] do
    resources :events, :only => [:index], :controller => "post_events"
    resources :favorites, only: [:index, :create, :destroy]
    resources :replacements, :only => [:index, :new, :create], :controller => "post_replacements"
    resource :artist_commentary, only: [:show] do
      collection { put :create_or_update }
      member { put :revert }
    end
    resource :votes, controller: "post_votes", only: [:create, :destroy], as: "post_votes"
    member do
      put :revert
      put :copy_notes
      get :show_seq
      put :mark_as_translated
    end
    get :similar, :to => "iqdb_queries#index"
  end
  resources :post_appeals
  resources :post_flags
  resources :post_approvals, only: [:create, :index]
  resources :post_disapprovals, only: [:create, :show, :index]
  resources :post_versions, :only => [:index, :search] do
    member do
      put :undo
    end
    collection do
      get :search
    end
  end
  resources :artist_commentaries, :only => [:index, :show] do
    collection do
      put :create_or_update
      get :search
    end
    member do
      put :revert
    end
  end
  resources :artist_commentary_versions, :only => [:index, :show]
  resources :rate_limits, only: [:index]
  resource :related_tag, :only => [:show, :update]
  resources :recommended_posts, only: [:index]
  resources :robots, only: [:index]
  resources :saved_searches, :except => [:show]
  resource :session, only: [:new, :create, :destroy] do
    get :confirm_password, on: :collection
    get :sign_out, on: :collection
  end
  resource :source, :only => [:show]
  resource :status, only: [:show], controller: "status"
  resources :tags
  resources :tag_aliases, only: [:show, :index, :destroy]
  resources :tag_implications, only: [:show, :index, :destroy]
  resources :uploads do
    collection do
      post :preprocess
      get :batch
      get :image_proxy
    end
  end
  resources :users do
    resources :favorites, only: [:index, :create, :destroy]
    resources :favorite_groups, controller: "favorite_groups", only: [:index], as: "favorite_groups"
    resource :email, only: [:show, :edit, :update] do
      get :verify
      post :send_confirmation
    end
    resource :password, only: [:edit, :update]
    resources :api_keys, only: [:new, :create, :edit, :update, :index, :destroy]

    collection do
      get :custom_style
    end
  end
  resources :user_upgrades, only: [:new, :create, :show, :index] do
    get :receipt, on: :member
    get :payment, on: :member
    put :refund, on: :member
  end
  resources :user_events, only: [:index]
  resources :user_feedbacks, except: [:destroy]
  resources :user_sessions, only: [:index]
  resources :user_name_change_requests, only: [:new, :create, :show, :index]
  resources :webhooks do
    post :receive, on: :collection
  end
  resources :wiki_pages, id: /.+?(?=\.json|\.xml|\.html)|.+/ do
    put :revert, on: :member
    get :search, on: :collection
    get :show_or_new, on: :collection
  end
  resources :wiki_page_versions, :only => [:index, :show, :diff] do
    collection do
      get :diff
    end
  end

  # Legacy Danbooru 1 API endpoints
  get "/tag/index.xml", :controller => "legacy", :action => "tags", :format => "xml"
  get "/tag/index.json", :controller => "legacy", :action => "tags", :format => "json"
  get "/post/index.xml", :controller => "legacy", :action => "posts", :format => "xml"
  get "/post/index.json", :controller => "legacy", :action => "posts", :format => "json"

  # Legacy Danbooru 1 redirects.
  get "/artist" => redirect {|params, req| "/artists?page=#{req.params[:page]}&search[name]=#{CGI.escape(req.params[:name].to_s)}"}
  get "/artist/show/:id" => redirect("/artists/%{id}")
  get "/artist/show" => redirect {|params, req| "/artists?name=#{CGI.escape(req.params[:name].to_s)}"}

  get "/forum" => redirect {|params, req| "/forum_topics?page=#{req.params[:page]}"}
  get "/forum/show/:id" => redirect {|params, req| "/forum_posts/#{req.params[:id]}?page=#{req.params[:page]}"}

  get "/pool/show/:id" => redirect("/pools/%{id}")

  get "/post/index" => redirect {|params, req| "/posts?tags=#{CGI.escape(req.params[:tags].to_s)}&page=#{req.params[:page]}"}
  get "/post/atom" => redirect {|params, req| "/posts.atom?tags=#{CGI.escape(req.params[:tags].to_s)}"}
  get "/post/show/:id/:tag_title" => redirect("/posts/%{id}")
  get "/post/show/:id" => redirect("/posts/%{id}")

  get "/tag" => redirect {|params, req| "/tags?page=#{req.params[:page]}&search[name_matches]=#{CGI.escape(req.params[:name].to_s)}&search[order]=#{req.params[:order]}&search[category]=#{req.params[:type]}"}

app/controllers/wiki_pages_controller.rb
class WikiPagesController < ApplicationController
  respond_to :html, :xml, :json, :js
  layout "sidebar"

  def new
    @wiki_page = authorize WikiPage.new(permitted_attributes(WikiPage))
    respond_with(@wiki_page)
  end

  def edit
    @wiki_page, _found_by = WikiPage.find_by_id_or_title(params[:id])
    authorize @wiki_page
    respond_with(@wiki_page)
  end

  def index
    if params[:title].present?
      redirect_to wiki_pages_path(search: { title_normalize: params[:title] }, redirect: true)
    else
      @wiki_pages = authorize WikiPage.paginated_search(params)
      respond_with(@wiki_pages)
    end
  end

  def search
    authorize WikiPage
    render layout: "default"
  end

  def show
    @wiki_page, found_by = WikiPage.find_by_id_or_title(params[:id])

    if request.format.html? && @wiki_page.blank? && found_by == :title
      @wiki_page = WikiPage.new(title: params[:id])
      respond_with @wiki_page, status: 404
    elsif request.format.html? && @wiki_page.present? && found_by == :id
      redirect_to @wiki_page
    elsif @wiki_page.blank?
      raise ActiveRecord::RecordNotFound
    else
      respond_with(@wiki_page)
    end
  end

  def create
    @wiki_page = authorize WikiPage.new(permitted_attributes(WikiPage))
    @wiki_page.save
    respond_with(@wiki_page)
  end

  def update
    @wiki_page, _found_by = WikiPage.find_by_id_or_title(params[:id])
    authorize @wiki_page

    @wiki_page.update(permitted_attributes(@wiki_page))
    flash[:notice] = @wiki_page.warnings.full_messages.join(".\n \n") if @wiki_page.warnings.any?

    respond_with(@wiki_page)
  end

  def destroy
    @wiki_page, _found_by = WikiPage.find_by_id_or_title(params[:id])
    authorize @wiki_page

    @wiki_page.update(is_deleted: true)
    respond_with(@wiki_page)
  end

  def revert
    @wiki_page, _found_by = WikiPage.find_by_id_or_title(params[:id])
    authorize @wiki_page

    @version = @wiki_page.versions.find(params[:version_id])
    @wiki_page.revert_to!(@version)
    flash[:notice] = "Page was reverted"
    respond_with(@wiki_page)
  end

  def show_or_new
    if params[:title].blank?
      redirect_to new_wiki_page_path(permitted_attributes(WikiPage))
    else
      redirect_to wiki_page_path(params[:title])
    end
  end

  private

  def item_matches_params(wiki_page)
    if params[:search][:title_normalize]
      wiki_page.title == WikiPage.normalize_title(params[:search][:title_normalize])
    else
      true
    end
  end
end

app/helpers/wiki_pages_helper.rb
module WikiPagesHelper
  def wiki_page_other_names_list(wiki_page)
    names_html = wiki_page.other_names.map do |name|
      link_to(name, "https://www.pixiv.net/tags/#{u(name)}/artworks", class: "wiki-other-name")
    end

    safe_join(names_html, " ")
  end
end

app/views/wiki_pages/_form.html.erb
<div id="form-content">
  <%= edit_form_for(@wiki_page, url: wiki_page_path(@wiki_page.id)) do |f| %>
    <%= f.input :title, error: false, input_html: { data: { autocomplete: "tag" } }, hint: "Change to rename this wiki page. Update any wikis linking to this page first." %>

    <% if !@wiki_page.tag&.artist? || @wiki_page.other_names.present? %>
      <%= f.input :other_names_string, as: :string, label: "Other names (#{link_to_wiki "help", "help:translated_tags"})".html_safe, hint: "Names used for this tag on other sites such as Pixiv. Separate with spaces." %>
    <% end %>

    <%= f.input :body, as: :dtext %>

    <% if policy(@wiki_page).can_edit_locked? %>
      <%= f.input :is_locked, label: "Locked", hint: "Locked wikis can only be edited by Builders." %>
    <% end %>

    <%= f.input :is_deleted, label: "Deleted", hint: "Check to mark this wiki page as deleted." %>

    <%= f.submit "Submit" %>
    <%= dtext_preview_button "wiki_page_body" %>
  <% end %>
</div>

app/views/wiki_pages/_posts.html.erb
<% if wiki_page.tag.present? && !wiki_page.tag.empty? %>
  <div class="recent-posts">
    <h2 class="recent-posts-header">
      <%= link_to "Posts", posts_path(tags: wiki_page.title) %>
    </h2>

    <%= render_post_gallery(wiki_page.tag.posts.limit(8), tags: wiki_page.title) %>
  </div>
<% end %>

app/views/wiki_pages/_recent_changes.html.erb
<section>
  <h2>Recent Changes (<%= link_to "all", wiki_page_versions_path %>)</h2>
  <ul>
    <% WikiPage.order(updated_at: :desc).includes(:tag).limit(25).each do |page| %>
      <li><%= link_to page.pretty_title, wiki_page_path(page), class: tag_class(page.tag) %></li>
    <% end %>
  </ul>
</section>

app/views/wiki_pages/_search.html.erb
<%= search_form_for(wiki_pages_path) do |f| %>
  <%= f.input :title_normalize, label: "Title", hint: "Use * for wildcard", input_html: { value: params[:search][:title_normalize], "data-autocomplete": "wiki-page" } %>
  <%= f.input :other_names_match, label: "Other names", hint: "Use * for wildcard", input_html: { value: params[:search][:other_names_match] } %>
  <%= f.input :title_or_body_matches, label: "Text", hint: "Use * for wildcard", input_html: { value: params[:search][:title_or_body_matches] } %>
  <%= f.input :linked_to, hint: "Find wikis linking to this wiki", input_html: { value: params[:search][:linked_to], "data-autocomplete": "wiki-page" } %>
  <%= f.input :is_deleted, label: "Deleted?", as: :select, include_blank: true, selected: params[:search][:is_deleted] %>
  <%= f.input :order, collection: [%w[Newest created_at], %w[Title title], %w[Posts post_count]], include_blank: true, selected: params[:search][:order] %>
  <%= f.submit "Search" %>
<% end %>

app/views/wiki_pages/_secondary_links.html.erb
<% content_for(:secondary_links) do %>
  <%= quick_search_form_for(:title_normalize, wiki_pages_path, "wiki pages", autocomplete: "wiki-page", redirect: true) %>
  <%= subnav_link_to "Listing", wiki_pages_path %>
  <%= subnav_link_to "Search", search_wiki_pages_path %>
  <% if policy(WikiPage).new? %>
    <%= subnav_link_to "New", new_wiki_page_path %>
  <% end %>
  <%= subnav_link_to "Help", wiki_page_path("help:wiki") %>
  <% if @wiki_page && @wiki_page.new_record? && @wiki_page.try(:tag).present? %>
    <li>|</li>
    <%= subnav_link_to "Posts (#{@wiki_page.tag.post_count})", posts_path(:tags => @wiki_page.title) %>
  <% elsif @wiki_page && !@wiki_page.new_record? %>
    <li>|</li>
    <%= subnav_link_to "Posts (#{@wiki_page.tag.try(:post_count) || 0})", posts_path(:tags => @wiki_page.title) %>
    <%= subnav_link_to "History", wiki_page_versions_path(:search => {:wiki_page_id => @wiki_page.id}) %>
    <% if policy(@wiki_page).edit? %>
      <%= subnav_link_to "Edit", edit_wiki_page_path(@wiki_page.id), "data-shortcut": "e" %>

      <% if current_page?(action: :edit) %>
        <% if @wiki_page.is_deleted? %>
          <%= subnav_link_to "Undelete", wiki_page_path(@wiki_page.id), remote: true, method: :put, "data-params": "wiki_page[is_deleted]=false", "data-shortcut": "shift+d", "data-confirm": "Are you sure you want to undelete this wiki?" %>
        <% else %>
          <%= subnav_link_to "Delete", wiki_page_path(@wiki_page.id), remote: true, method: :put, "data-params": "wiki_page[is_deleted]=true", "data-shortcut": "shift+d", "data-confirm": "Are you sure you want to delete this wiki?" %>
        <% end %>
      <% end %>
    <% end %>
  <% elsif @wiki_page_version %>
    <li>|</li>
    <%= subnav_link_to "Newest", wiki_page_path(@wiki_page_version.wiki_page_id) %>
    <% if @wiki_page_version.previous %>
      <%= subnav_link_to "Diff", diff_wiki_page_versions_path(:otherpage => @wiki_page_version.id, :thispage => @wiki_page_version.previous.id) %>
    <% end %>
    <% if policy(@wiki_page_version.wiki_page).revert? %>
      <%= subnav_link_to "Revert to", revert_wiki_page_path(@wiki_page_version.wiki_page_id, :version_id => @wiki_page_version.id), :method => :put, :data => {:confirm => "Are you sure you want to revert to this version?"} %>
    <% end %>
  <% end %>
<% end %>

app/views/wiki_pages/_sidebar.html.erb
<% content_for(:sidebar) do %>
  <%= render "posts/partials/index/blacklist" %>
  <%= render "wiki_pages/recent_changes" %>

  <% if @wiki_page.present? %>
    <h2>Options</h2>

    <ul>
      <% unless @wiki_page.is_meta_wiki? %>
        <li><%= link_to "Tag History", post_versions_path(search: { changed_tags: @wiki_page.title }) %></li>
      <% end %>
      <li><%= link_to "Wiki History", wiki_page_versions_path(search: { wiki_page_id: @wiki_page.id }) %></li>
      <li><%= link_to "Discussions", forum_posts_path(search: { linked_to: @wiki_page.title }) %></li>
      <li><%= link_to "What Links Here", wiki_pages_path(search: { linked_to: @wiki_page.title }) %></li>
    </ul>
  <% end %>
<% end %>

app/views/wiki_pages/edit.html.erb
<%= render "sidebar" %>

<% content_for(:content) do %>
  <h1>Edit Wiki</h1>

  <%= render "form" %>
<% end %>

<%= render "secondary_links" %>

app/views/wiki_pages/index.html.erb
<%= render "sidebar" %>

<% content_for(:content) do %>
  <h1>Wiki</h1>

  <%= render "search" %>

  <%= table_for @wiki_pages, width: "100%" do |t| %>
    <% t.column "Title" do |wiki_page| %>
      <span class="<%= tag_class(wiki_page.tag) %>"><%= link_to_wiki wiki_page.title %></span>
    <% end %>
    <% t.column "Last edited" do |wiki_page| %>
      <%= time_ago_in_words_tagged(wiki_page.updated_at) %>
    <% end %>
  <% end %>

  <%= numbered_paginator(@wiki_pages) %>
<% end %>

<%= render "secondary_links" %>

app/views/wiki_pages/new.html.erb
<%= render "sidebar" %>

<% content_for(:content) do %>
  <h1>New Wiki Page</h1>

  <% if @wiki_page.title.present? %>
    <div class="notice notice-info notice-small" id="new-wiki-page-notice">
      This wiki page does not yet exist. The form below will allow you to create a new page for <%= @wiki_page.title %>. It will act as an explanation on how to use the tag for other users on the site.
    </div>
  <% end %>

  <%= edit_form_for(@wiki_page) do |f| %>
    <%= f.input :title, error: false, input_html: { data: { autocomplete: "tag" } } %>
    <%= f.input :other_names_string, as: :string, label: "Other names (#{link_to_wiki "help", "help:translated_tags"})".html_safe, hint: "Names used for this tag on other sites such as Pixiv. Separate with spaces." %>
    <%= f.input :body, as: :dtext %>
    <%= f.submit "Submit" %>
    <%= dtext_preview_button "wiki_page_body" %>
  <% end %>

  <%= render "tag_relationships/alias_and_implication_list", tag: @wiki_page.tag %>
  <%= render "wiki_pages/posts", wiki_page: @wiki_page %>
<% end %>

<%= render "secondary_links" %>

app/views/wiki_pages/search.html.erb
<div id="c-wiki-pages">
  <div id="a-search">
    <%= render "search" %>
  </div>
</div>

<%= render "secondary_links" %>

app/views/wiki_pages/show.html.erb
<% page_title "#{@wiki_page.pretty_title.titleize} Wiki" %>
<% meta_description DText.excerpt(@wiki_page.body) %>

<% if @wiki_page.artist.present? && @wiki_page.artist.is_banned? %>
  <% noindex %>
<% end %>

<%= render "secondary_links" %>
<%= render "sidebar" %>

<% content_for(:content) do %>
  <h1 id="wiki-page-title">
    <%= link_to @wiki_page.pretty_title, posts_path(tags: @wiki_page.title), class: tag_class(@wiki_page.tag) %>

    <% if @wiki_page.is_locked? %>
      (locked)
    <% end %>

    <% if @wiki_page.is_deleted? %>
      (deleted)
    <% end %>
  </h1>

  <div id="wiki-page-body" class="prose">
    <% if @wiki_page.other_names.present? %>
      <p><%= wiki_page_other_names_list(@wiki_page) %></p>
    <% end %>

    <% if @wiki_page.new_record? %>
      <p>This wiki page does not exist. <%= link_to "Create new wiki page", new_wiki_page_path(wiki_page: { title: @wiki_page.title }), rel: "nofollow" %>.</p>
    <% else %>
      <%= format_text(@wiki_page.body) %>
    <% end %>

    <% if @wiki_page.artist.present? && !@wiki_page.artist.is_deleted? %>
      <p><%= link_to "View artist", @wiki_page.artist %></p>
    <% end %>

    <%= render "tag_relationships/alias_and_implication_list", tag: @wiki_page.tag %>
  </div>

  <%= render "wiki_pages/posts", wiki_page: @wiki_page %>
<% end %>

app/views/wiki_pages/update.js.erb
location.reload();