config/routes.rb
# This file contains configuration for Danbooru's URL routes. It defines all the
# URL endpoints and HTTP redirects used by Danbooru.
#
# A list of routes can be found at http://localhost:3000/rails/info/routes when
# running the server in development mode. You can also run `bin/rails routes` to
# produce a list of routes.
#
# @see https://guides.rubyonrails.org/routing.html
# @see http://localhost:3000/rails/info/routes
Rails.application.routes.draw do
  resources :posts, only: [:index, :show, :update, :destroy] do
    get :random, on: :collection
  end

  resources :autocomplete, only: [:index]

  # XXX This comes *after* defining posts above because otherwise the paginator
  # generates `/?page=2` instead of `/posts?page=2` on the posts#index page.
  root "posts#index"

  namespace :admin do
    resources :users, :only => [:edit, :update]
  end
  namespace :moderator do
    resource :dashboard, :only => [:show]
    resources :ip_addrs, :only => [:index] do
      collection do
        get :search
      end
    end
    namespace :post do
      resources :posts, :only => [:delete, :expunge, :confirm_delete] do
        member do
          post :expunge
          get :confirm_move_favorites
          post :move_favorites
          post :ban
          post :unban
        end
      end
    end
    resources :ip_addrs, :only => [:index, :search] do
      collection do
        get :search
      end
    end
  end
  namespace :explore do
    resources :posts, :only => [] do
      collection do
        get :popular
        get :curated
        get :viewed
        get :searches
        get :missed_searches
      end
    end
  end
  namespace :maintenance do
    namespace :user do
      resource :count_fixes, only: [:new, :create]
      resource :email_notification, :only => [:show, :destroy]
      resource :deletion, :only => [:show, :destroy]
    end
  end

  resources :api_keys, only: [:new, :create, :edit, :update, :index, :destroy]

  resources :artists do
    member do
      put :revert
      put :ban
      put :unban
    end
    collection do
      get :show_or_new
      get :banned
    end
  end
  resources :artist_urls, only: [:index]
  resources :artist_versions, :only => [:index, :show] do
    collection do
      get :search
    end
  end
  resources :bans
  resources :bulk_update_requests do
    member do
      post :approve
    end
  end
  resources :comment_votes, only: [:index, :show, :destroy]
  resources :comments do
    resource :votes, controller: "comment_votes", only: [:create, :destroy], as: "comment_votes" do
      get "/", action: :index
    end
    collection do
      get :search
    end
    member do
      post :undelete
    end
  end
  resources :counts do
    collection do
      get :posts
    end
  end
  resources :delayed_jobs, :only => [:index, :destroy] do
    member do
      put :run
      put :retry
      put :cancel
    end
  end
  resources :dmails, :only => [:new, :create, :update, :index, :show] do
    collection do
      post :mark_all_as_read
    end
  end
  resource  :dtext_preview, :only => [:create]
  resources :dtext_links, only: [:index]
  resources :emails, only: [:index, :show]
  resources :favorites, :only => [:index, :create, :destroy]
  resources :favorite_groups do
    member do
      put :add_post
    end
    resource :order, :only => [:edit], :controller => "favorite_group_orders"
  end
  resources :forum_posts do
    member do
      post :undelete
    end
    collection do
      get :search
    end
  end
  resources :forum_post_votes, only: [:index, :show, :create, :destroy]
  resources :forum_topics do
    member do
      post :undelete
    end
    collection do
      post :mark_all_as_read
    end
  end
  resources :forum_topic_visits, only: [:index]
  resources :ip_bans, only: [:index, :new, :create, :update]
  resources :ip_addresses, only: [:show, :index], id: /.+?(?=\.json|\.xml|\.html)|.+/
  resources :ip_geolocations, only: [:index]
  resource :iqdb_queries, :only => [:show, :create] do
    collection do
      get :preview
      get :check, to: redirect {|path_params, req| "/iqdb_queries?#{req.query_string}"}
    end
  end
  resources :media_assets, only: [:index, :show]
  resources :media_metadata, only: [:index]
  resources :mod_actions
  resources :moderation_reports, only: [:new, :create, :index, :show]
  resources :modqueue, only: [:index]
  resources :news_updates
  resources :notes do
    member do
      put :revert
    end
  end
  resources :note_versions, :only => [:index, :show]
  resource :note_previews, :only => [:show]
  resource :password_reset, only: [:create, :show]
  resources :pixiv_ugoira_frame_data, only: [:index]
  resources :pools do
    member do
      put :revert
      post :undelete
    end
    collection do
      get :gallery
    end
    resource :order, :only => [:edit], :controller => "pool_orders"
  end
  resource :pool_element, :only => [:create]
  resources :pool_versions, :only => [:index] do
    member do
      get :diff
    end
    collection do
      get :search
    end
  end
  resources :post_regenerations, :only => [:create]
  resources :post_replacements, :only => [:index, :new, :create, :update]
  resources :post_votes, only: [:index, :show, :create, :destroy]

  # XXX Use `only: []` to avoid redefining post routes defined at top of file.
  resources :posts, only: [] do
    resources :events, :only => [:index], :controller => "post_events"
    resources :favorites, only: [:index, :create, :destroy]
    resources :replacements, :only => [:index, :new, :create], :controller => "post_replacements"
    resource :artist_commentary, only: [:show] do
      collection { put :create_or_update }
      member { put :revert }
    end
    resource :votes, controller: "post_votes", only: [:create, :destroy], as: "post_votes"
    member do
      put :revert
      put :copy_notes
      get :show_seq
      put :mark_as_translated
    end
    get :similar, :to => "iqdb_queries#index"
  end
  resources :post_appeals
  resources :post_flags
  resources :post_approvals, only: [:create, :index]
  resources :post_disapprovals, only: [:create, :show, :index]
  resources :post_versions, :only => [:index, :search] do
    member do
      put :undo
    end
    collection do
      get :search
    end
  end
  resources :artist_commentaries, :only => [:index, :show] do
    collection do
      put :create_or_update
      get :search
    end
    member do
      put :revert
    end
  end
  resources :artist_commentary_versions, :only => [:index, :show]
  resources :rate_limits, only: [:index]
  resource :related_tag, :only => [:show, :update]
  resources :recommended_posts, only: [:index]
  resources :robots, only: [:index]
  resources :saved_searches, :except => [:show]
  resource :session, only: [:new, :create, :destroy] do
    get :confirm_password, on: :collection
    get :sign_out, on: :collection
  end
  resource :source, :only => [:show]
  resource :status, only: [:show], controller: "status"
  resources :tags
  resources :tag_aliases, only: [:show, :index, :destroy]
  resources :tag_implications, only: [:show, :index, :destroy]
  resources :uploads do
    collection do
      post :preprocess
      get :batch
      get :image_proxy
    end
  end
  resources :users do
    resources :favorites, only: [:index, :create, :destroy]
    resources :favorite_groups, controller: "favorite_groups", only: [:index], as: "favorite_groups"
    resource :email, only: [:show, :edit, :update] do
      get :verify
      post :send_confirmation
    end
    resource :password, only: [:edit, :update]
    resources :api_keys, only: [:new, :create, :edit, :update, :index, :destroy]

    collection do
      get :custom_style
    end
  end
  resources :user_upgrades, only: [:new, :create, :show, :index] do
    get :receipt, on: :member
    get :payment, on: :member
    put :refund, on: :member
  end
  resources :user_events, only: [:index]
  resources :user_feedbacks, except: [:destroy]
  resources :user_sessions, only: [:index]
  resources :user_name_change_requests, only: [:new, :create, :show, :index]
  resources :webhooks do
    post :receive, on: :collection
  end
  resources :wiki_pages, id: /.+?(?=\.json|\.xml|\.html)|.+/ do
    put :revert, on: :member
    get :search, on: :collection
    get :show_or_new, on: :collection
  end
  resources :wiki_page_versions, :only => [:index, :show, :diff] do
    collection do
      get :diff
    end
  end

  # Legacy Danbooru 1 API endpoints
  get "/tag/index.xml", :controller => "legacy", :action => "tags", :format => "xml"
  get "/tag/index.json", :controller => "legacy", :action => "tags", :format => "json"
  get "/post/index.xml", :controller => "legacy", :action => "posts", :format => "xml"
  get "/post/index.json", :controller => "legacy", :action => "posts", :format => "json"

  # Legacy Danbooru 1 redirects.
  get "/artist" => redirect {|params, req| "/artists?page=#{req.params[:page]}&search[name]=#{CGI.escape(req.params[:name].to_s)}"}
  get "/artist/show/:id" => redirect("/artists/%{id}")
  get "/artist/show" => redirect {|params, req| "/artists?name=#{CGI.escape(req.params[:name].to_s)}"}

  get "/forum" => redirect {|params, req| "/forum_topics?page=#{req.params[:page]}"}
  get "/forum/show/:id" => redirect {|params, req| "/forum_posts/#{req.params[:id]}?page=#{req.params[:page]}"}

  get "/pool/show/:id" => redirect("/pools/%{id}")

  get "/post/index" => redirect {|params, req| "/posts?tags=#{CGI.escape(req.params[:tags].to_s)}&page=#{req.params[:page]}"}
  get "/post/atom" => redirect {|params, req| "/posts.atom?tags=#{CGI.escape(req.params[:tags].to_s)}"}
  get "/post/show/:id/:tag_title" => redirect("/posts/%{id}")
  get "/post/show/:id" => redirect("/posts/%{id}")

  get "/tag" => redirect {|params, req| "/tags?page=#{req.params[:page]}&search[name_matches]=#{CGI.escape(req.params[:name].to_s)}&search[order]=#{req.params[:order]}&search[category]=#{req.params[:type]}"}

app/models/post_disapproval.rb
class PostDisapproval < ApplicationRecord
  DELETION_THRESHOLD = 1.month
  REASONS = %w[breaks_rules poor_quality disinterest]

  belongs_to :post
  belongs_to :user
  validates :user, uniqueness: { scope: :post, message: "have already hidden this post" }
  validates :reason, inclusion: { in: REASONS }
  validate :validate_disapproval

  scope :with_message, -> { where.not(message: nil) }
  scope :without_message, -> { where(message: nil) }
  scope :breaks_rules, -> {where(:reason => "breaks_rules")}
  scope :poor_quality, -> {where(:reason => "poor_quality")}
  scope :disinterest, -> {where(:reason => "disinterest")}

  def self.prune!
    PostDisapproval.where("post_id in (select _.post_id from post_disapprovals _ where _.created_at < ?)", DELETION_THRESHOLD.ago).delete_all
  end

  concerning :SearchMethods do
    class_methods do
      def creator_matches(creator, searcher)
        return none if creator.nil?

        policy = Pundit.policy!(searcher, PostDisapproval.new(user: creator))

        if policy.can_view_creator?
          where(user: creator)
        else
          none
        end
      end

      def search(params)
        q = search_attributes(params, :id, :created_at, :updated_at, :message, :reason, :post)
        q = q.text_attribute_matches(:message, params[:message_matches])

        q = q.with_message if params[:has_message].to_s.truthy?
        q = q.without_message if params[:has_message].to_s.falsy?

        if params[:user_id].present?
          user = User.find(params[:user_id])
          q = q.creator_matches(user, CurrentUser.user)
        elsif params[:user_name].present?
          user = User.find_by_name(params[:user_name])
          q = q.creator_matches(user, CurrentUser.user)
        end

        case params[:order]
        when "post_id", "post_id_desc"
          q = q.order(post_id: :desc, id: :desc)
        else
          q = q.apply_default_order(params)
        end

        q
      end
    end
  end

  def self.available_includes
    [:user, :post]
  end

  def validate_disapproval
    if post.is_active?
      errors.add(:post, "is already active and cannot be disapproved")
    end
  end

  def message=(message)
    message = nil if message.blank?
    super(message)
  end
end

app/controllers/post_disapprovals_controller.rb
class PostDisapprovalsController < ApplicationController
  respond_to :js, :html, :json, :xml

  def create
    @post_disapproval = authorize PostDisapproval.new(user: CurrentUser.user, **permitted_attributes(PostDisapproval))
    @post_disapproval.save
    respond_with(@post_disapproval)
  end

  def index
    @post_disapprovals = authorize PostDisapproval.paginated_search(params)
    @post_disapprovals = @post_disapprovals.includes(:user) if request.format.html?

    respond_with(@post_disapprovals)
  end
end

app/views/post_disapprovals/_compact_counts.html.erb
<% if (CurrentUser.can_approve_posts? || post.created_at < Danbooru.config.moderation_period.ago) && disapprovals.length > 0 %>
  <% if disapprovals.map(&:reason).grep("breaks_rules").count > 0 %>
    (breaks rules: <%= disapprovals.map(&:reason).grep("breaks_rules").count %>)
  <% end %>

  <% if disapprovals.map(&:reason).grep("poor_quality").count > 0 %>
    (poor quality: <%= disapprovals.map(&:reason).grep("poor_quality").count %>)
  <% end %>

  <% if disapprovals.map(&:reason).grep(/disinterest|legacy/).count > 0 %>
    (no interest: <%= disapprovals.map(&:reason).grep(/disinterest|legacy/).count %>)
  <% end %>

  <% if disapprovals.map(&:message).any?(&:present?) %>
    (messages: <%= disapprovals.map(&:message).select(&:present?).map { |msg| format_text(msg, inline: true) }.to_sentence.html_safe %>)
  <% end %>
<% end %>

app/views/post_disapprovals/_counts.html.erb
<% if (CurrentUser.can_approve_posts? || post.created_at < Danbooru.config.moderation_period.ago) && disapprovals.length > 0 %>
  <p>
    It has been reviewed by <%= pluralize disapprovals.length, "approver" %>.

    <% if disapprovals.map(&:reason).grep("breaks_rules").count > 0 %>
      <%= disapprovals.map(&:reason).grep("breaks_rules").count %> believe it breaks the rules.
    <% end %>

    <% if disapprovals.map(&:reason).grep("poor_quality").count > 0 %>
      <%= disapprovals.map(&:reason).grep("poor_quality").count %> believe it has poor quality.
    <% end %>

    <% if disapprovals.map(&:reason).grep(/disinterest|legacy/).count > 0 %>
      <%= disapprovals.map(&:reason).grep(/disinterest|legacy/).count %> did not like the post enough to approve it.
    <% end %>

    <% if disapprovals.map(&:message).any?(&:present?) %>
      Messages: <%= disapprovals.map(&:message).select(&:present?).map { |msg| "\"#{format_text(msg, inline: true)}\"" }.to_sentence.html_safe %>.
    <% end %>
  </p>
<% end %>

app/views/post_disapprovals/_detailed_rejection_dialog.html.erb
<div id="detailed-rejection-dialog" title="Detailed Rejection" style="display: none;">
  <p>You can supply a short message to the uploader explaining why you rejected this upload.</p>

  <%= edit_form_for(PostDisapproval.new, url: post_disapprovals_path, remote: true, html: { id: "detailed-rejection-form" }) do |f| %>
    <%= f.hidden_field :post_id, value: "x" %>
    <%= f.input :reason, collection: PostDisapproval::REASONS.map { |x| [x.humanize, x] } %>
    <%= f.input :message, as: :string %>
  <% end %>
</div>

app/views/post_disapprovals/create.js.erb
if ($("#c-posts #a-show").length) {
  location.reload();
} else if ($("#c-modqueue").length) {
  $("#c-modqueue #post-<%= @post_disapproval.post.id %>").hide();
  Danbooru.notice("Post was hidden");
}

app/views/post_disapprovals/index.html.erb
<div id="c-post-disapprovals">
  <div id="a-index">
    <h1>Disapprovals</h1>

    <%= search_form_for(post_disapprovals_path) do |f| %>
      <%= f.input :user_name, label: "Creator", input_html: { value: params[:search][:user_name], "data-autocomplete": "user" } %>
      <%= f.input :post_id, label: "Post ID", input_html: { value: params[:search][:post_id] } %>
      <%= f.input :post_tags_match, label: "Tags", input_html: { value: params[:search][:post_tags_match], data: { autocomplete: "tag-query" } } %>
      <%= f.input :message_matches, label: "Message", input_html: { value: params[:search][:message_matches] } %>
      <%= f.input :reason, label: "Reason", collection: PostDisapproval::REASONS.map { |x| [x.humanize, x] }, include_blank: true, selected: params[:search][:reason] %>
      <%= f.input :has_message, label: "Has Message?", collection: %w[Yes No], include_blank: true, selected: params[:search][:has_message] %>
      <%= f.input :order, collection: [["ID", "id_desc"], ["Post ID", "post_id_desc"]], selected: params[:search][:order] %>
      <%= f.submit "Search" %>
    <% end %>

    <%= table_for @post_disapprovals, class: "striped autofit", width: "100%" do |t| %>
      <% t.column "Post" do |post_disapproval| %>
        <%= link_to "post ##{post_disapproval.post_id}", post_path(post_disapproval.post_id) %>
        <%= link_to "»", post_disapprovals_path(search: params[:search].merge(post_id: post_disapproval.post_id)) %>
      <% end %>
      <% t.column "Message", td: {class: "col-expand"} do |post_disapproval| %>
        <div class="prose">
          <%= format_text(post_disapproval.message) %>
        </div>
      <% end %>
      <% t.column "Reason" do |post_disapproval| %>
        <%= link_to post_disapproval.reason.humanize, post_disapprovals_path(search: params[:search].merge(reason: post_disapproval.reason)) %>
      <% end %>
      <% t.column "Created" do |post_disapproval| %>
        <% if policy(post_disapproval).can_view_creator? %>
          <%= link_to_user post_disapproval.user %>
          <%= link_to "»", post_disapprovals_path(search: params[:search].merge(user_name: post_disapproval.user&.name)) %>
        <% end %>

        <p>
          <%= compact_time(post_disapproval.updated_at) %>
        </p>
      <% end %>
    <% end %>

    <%= numbered_paginator(@post_disapprovals) %>
  </div>
</div>