config/routes.rb
    collection do
      get :search
    end
  end
  resources :bans
  resources :bulk_update_requests do
    member do
      post :approve
    end
  end
  resources :comment_votes, only: [:index, :show, :destroy]
  resources :comments do
    resource :votes, controller: "comment_votes", only: [:create, :destroy], as: "comment_votes" do
      get "/", action: :index
    end
    collection do
      get :search
    end
    member do
      post :undelete
    end
  end
  resources :counts do
    collection do
      get :posts
    end
  end
  resources :delayed_jobs, :only => [:index, :destroy] do
    member do
      put :run
      put :retry
      put :cancel
    end
  end
  resources :dmails, :only => [:new, :create, :update, :index, :show] do
    collection do
      post :mark_all_as_read
    end
  end
  resource  :dtext_preview, :only => [:create]
  resources :dtext_links, only: [:index]
  resources :emails, only: [:index, :show]
  resources :favorites, :only => [:index, :create, :destroy]
  resources :favorite_groups do
    member do
      put :add_post
    end
    resource :order, :only => [:edit], :controller => "favorite_group_orders"
  end
  resources :forum_posts do
    member do
      post :undelete
    end
    collection do
      get :search
    end
  end
  resources :forum_post_votes, only: [:index, :show, :create, :destroy]
  resources :forum_topics do
    member do
      post :undelete
    end
    collection do
      post :mark_all_as_read
    end
  end
  resources :forum_topic_visits, only: [:index]
  resources :ip_bans, only: [:index, :new, :create, :update]
  resources :ip_addresses, only: [:show, :index], id: /.+?(?=\.json|\.xml|\.html)|.+/
  resources :ip_geolocations, only: [:index]
  resource :iqdb_queries, :only => [:show, :create] do
    collection do
      get :preview
      get :check, to: redirect {|path_params, req| "/iqdb_queries?#{req.query_string}"}
    end
  end
  resources :media_assets, only: [:index, :show]
  resources :media_metadata, only: [:index]
  resources :mod_actions
  resources :moderation_reports, only: [:new, :create, :index, :show]
  resources :modqueue, only: [:index]
  resources :news_updates
  resources :notes do
    member do
      put :revert
    end
  end
  resources :note_versions, :only => [:index, :show]
  resource :note_previews, :only => [:show]
  resource :password_reset, only: [:create, :show]
  resources :pixiv_ugoira_frame_data, only: [:index]
  resources :pools do
    member do
      put :revert
      post :undelete
    end
    collection do
      get :gallery
    end
    resource :order, :only => [:edit], :controller => "pool_orders"
  end
  resource :pool_element, :only => [:create]
  resources :pool_versions, :only => [:index] do
    member do
      get :diff
    end
    collection do
      get :search
    end
  end
  resources :post_regenerations, :only => [:create]
  resources :post_replacements, :only => [:index, :new, :create, :update]
  resources :post_votes, only: [:index, :show, :create, :destroy]

  # XXX Use `only: []` to avoid redefining post routes defined at top of file.
  resources :posts, only: [] do
    resources :events, :only => [:index], :controller => "post_events"
    resources :favorites, only: [:index, :create, :destroy]
    resources :replacements, :only => [:index, :new, :create], :controller => "post_replacements"
    resource :artist_commentary, only: [:show] do
      collection { put :create_or_update }
      member { put :revert }
    end
    resource :votes, controller: "post_votes", only: [:create, :destroy], as: "post_votes"
    member do
      put :revert
      put :copy_notes
      get :show_seq
      put :mark_as_translated
    end
    get :similar, :to => "iqdb_queries#index"
  end
  resources :post_appeals
  resources :post_flags
  resources :post_approvals, only: [:create, :index]
  resources :post_disapprovals, only: [:create, :show, :index]
  resources :post_versions, :only => [:index, :search] do
    member do
      put :undo
    end
    collection do
      get :search
    end
  end
  resources :artist_commentaries, :only => [:index, :show] do
    collection do
      put :create_or_update
      get :search
    end
    member do
      put :revert
    end
  end
  resources :artist_commentary_versions, :only => [:index, :show]
  resources :rate_limits, only: [:index]
  resource :related_tag, :only => [:show, :update]
  resources :recommended_posts, only: [:index]
  resources :robots, only: [:index]
  resources :saved_searches, :except => [:show]
  resource :session, only: [:new, :create, :destroy] do
    get :confirm_password, on: :collection
    get :sign_out, on: :collection
  end
  resource :source, :only => [:show]
  resource :status, only: [:show], controller: "status"
  resources :tags
  resources :tag_aliases, only: [:show, :index, :destroy]
  resources :tag_implications, only: [:show, :index, :destroy]
  resources :uploads do
    collection do
      post :preprocess
      get :batch
      get :image_proxy
    end
  end
  resources :users do
    resources :favorites, only: [:index, :create, :destroy]
    resources :favorite_groups, controller: "favorite_groups", only: [:index], as: "favorite_groups"
    resource :email, only: [:show, :edit, :update] do
      get :verify
      post :send_confirmation
    end
    resource :password, only: [:edit, :update]
    resources :api_keys, only: [:new, :create, :edit, :update, :index, :destroy]

    collection do
      get :custom_style
    end
  end
  resources :user_upgrades, only: [:new, :create, :show, :index] do
    get :receipt, on: :member
    get :payment, on: :member
    put :refund, on: :member
  end
  resources :user_events, only: [:index]
  resources :user_feedbacks, except: [:destroy]
  resources :user_sessions, only: [:index]
  resources :user_name_change_requests, only: [:new, :create, :show, :index]
  resources :webhooks do
    post :receive, on: :collection
  end
  resources :wiki_pages, id: /.+?(?=\.json|\.xml|\.html)|.+/ do
    put :revert, on: :member
    get :search, on: :collection
    get :show_or_new, on: :collection
  end
  resources :wiki_page_versions, :only => [:index, :show, :diff] do
    collection do
      get :diff
    end
  end

  # Legacy Danbooru 1 API endpoints
  get "/tag/index.xml", :controller => "legacy", :action => "tags", :format => "xml"
  get "/tag/index.json", :controller => "legacy", :action => "tags", :format => "json"
  get "/post/index.xml", :controller => "legacy", :action => "posts", :format => "xml"
  get "/post/index.json", :controller => "legacy", :action => "posts", :format => "json"

  # Legacy Danbooru 1 redirects.
  get "/artist" => redirect {|params, req| "/artists?page=#{req.params[:page]}&search[name]=#{CGI.escape(req.params[:name].to_s)}"}
  get "/artist/show/:id" => redirect("/artists/%{id}")
  get "/artist/show" => redirect {|params, req| "/artists?name=#{CGI.escape(req.params[:name].to_s)}"}

  get "/forum" => redirect {|params, req| "/forum_topics?page=#{req.params[:page]}"}
  get "/forum/show/:id" => redirect {|params, req| "/forum_posts/#{req.params[:id]}?page=#{req.params[:page]}"}

  get "/pool/show/:id" => redirect("/pools/%{id}")

  get "/post/index" => redirect {|params, req| "/posts?tags=#{CGI.escape(req.params[:tags].to_s)}&page=#{req.params[:page]}"}
  get "/post/atom" => redirect {|params, req| "/posts.atom?tags=#{CGI.escape(req.params[:tags].to_s)}"}
  get "/post/show/:id/:tag_title" => redirect("/posts/%{id}")
  get "/post/show/:id" => redirect("/posts/%{id}")

  get "/tag" => redirect {|params, req| "/tags?page=#{req.params[:page]}&search[name_matches]=#{CGI.escape(req.params[:name].to_s)}&search[order]=#{req.params[:order]}&search[category]=#{req.params[:type]}"}
  get "/tag/index" => redirect {|params, req| "/tags?page=#{req.params[:page]}&search[name_matches]=#{CGI.escape(req.params[:name].to_s)}&search[order]=#{req.params[:order]}"}

  get "/user/show/:id" => redirect("/users/%{id}")

  get "/wiki/show" => redirect {|params, req| "/wiki_pages?title=#{CGI.escape(req.params[:title].to_s)}"}
  get "/help/:title" => redirect {|params, req| "/wiki_pages?title=#{CGI.escape('help:' + req.params[:title])}"}

  get "/login", to: "sessions#new", as: :login
  get "/logout", to: "sessions#sign_out", as: :logout
  get "/profile", to: "users#profile", as: :profile
  get "/settings", to: "users#settings", as: :settings

  get "/sitemap" => "static#sitemap_index"
  get "/opensearch" => "static#opensearch", :as => "opensearch"
  get "/privacy" => "static#privacy_policy", :as => "privacy_policy"
  get "/terms_of_service" => "static#terms_of_service", :as => "terms_of_service"
  get "/static/keyboard_shortcuts" => "static#keyboard_shortcuts", :as => "keyboard_shortcuts"
  get "/static/bookmarklet" => "static#bookmarklet", :as => "bookmarklet"
  get "/static/site_map" => "static#site_map", :as => "site_map"
  get "/static/colors" => "static#colors", :as => "colors"
  get "/static/contact" => "static#contact", :as => "contact"
  get "/static/dtext_help" => "static#dtext_help", :as => "dtext_help"
  get "/static/terms_of_service", to: redirect("/terms_of_service")
  get "/user_upgrade/new", to: redirect("/user_upgrades/new")

  get "/mock/recommender/recommend/:user_id" => "mock_services#recommender_recommend", as: "mock_recommender_recommend"
  get "/mock/recommender/similiar/:post_id" => "mock_services#recommender_similar", as: "mock_recommender_similar"
  get "/mock/reportbooru/missed_searches" => "mock_services#reportbooru_missed_searches", as: "mock_reportbooru_missed_searches"
  get "/mock/reportbooru/post_searches/rank" => "mock_services#reportbooru_post_searches", as: "mock_reportbooru_post_searches"
  get "/mock/reportbooru/post_views/rank" => "mock_services#reportbooru_post_views", as: "mock_reportbooru_post_views"
  get "/mock/iqdb/query" => "mock_services#iqdb_query", as: "mock_iqdb_query"
  post "/mock/iqdb/query" => "mock_services#iqdb_query"

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  respond_to :html, :xml, :json

  def edit
    @tag = authorize Tag.find(params[:id])
    respond_with(@tag)
  end

  def index
    if request.format.html?
      @tags = authorize Tag.paginated_search(params, defaults: { hide_empty: true })
    else
      @tags = authorize Tag.paginated_search(params)
    end

    @tags = @tags.includes(:consequent_aliases) if request.format.html?
    respond_with(@tags)
  end

  def show
    @tag = authorize Tag.find(params[:id])
    respond_with(@tag)
  end

  def update
    @tag = authorize Tag.find(params[:id])
    @tag.update(permitted_attributes(@tag))
    respond_with(@tag)
  end
end

app/helpers/tags_helper.rb
module TagsHelper
  def tag_class(tag)
    return nil if tag.blank?
    "tag-type-#{tag.category}"
  end
end

app/views/tags/_search.html.erb
<%= search_form_for(tags_path) do |f| %>
  <%= f.input :name_or_alias_matches, label: "Name", hint: "Use * for wildcard", input_html: { value: params[:search][:name_or_alias_matches], data: { autocomplete: "tag" } } %>
  <%= f.input :category, label: "Category", collection: TagCategory.canonical_mapping.to_a, include_blank: true,selected: params[:search][:category] %>
  <%= f.input :order, collection: [%w[Newest date], %w[Count count], %w[Name name]], include_blank: false, selected: params[:search][:order] %>
  <%= f.input :hide_empty, label: "Hide empty?", collection: %w[yes no], selected: params[:search][:hide_empty] %>
  <%= f.input :has_wiki_page, label: "Has wiki?", collection: %w[yes no], include_blank: true, selected: params[:search][:has_wiki_page] %>
  <%= f.input :has_artist, label: "Has artist?", collection: %w[yes no], include_blank: true, selected: params[:search][:has_artist] %>
  <%= f.submit "Search" %>
<% end %>

app/views/tags/_secondary_links.html.erb
<% content_for(:secondary_links) do %>
  <%= quick_search_form_for(:name_matches, tags_path, "tags", autocomplete: "tag") %>
  <%= subnav_link_to "Tags", tags_path %>
  <%= subnav_link_to("Aliases", tag_aliases_path) %>
  <%= subnav_link_to("Implications", tag_implications_path) %>
  <%= subnav_link_to "Request alias/implication", new_bulk_update_request_path %>
  <%= subnav_link_to "Related tags", related_tag_path %>
  <%= subnav_link_to "Help", wiki_page_path("help:tags") %>

  <% if @tag %>
    <li>|</li>
    <%= subnav_link_to "Posts (#{@tag.post_count})", posts_path(:tags => @tag.name) %>
    <%= subnav_link_to "Edit", edit_tag_path(@tag) %>
  <% end %>
<% end %>

app/views/tags/edit.html.erb
<div id="c-tags">
  <div id="a-edit">
    <h1>Tag: <%= @tag.name %></h1>

    <%= edit_form_for(@tag) do |f| %>
      <% if @tag.is_locked? %>
        <p>This tag is category locked</p>
      <% else %>
        <%= f.input :category, :collection => TagCategory.canonical_mapping.to_a, :include_blank => false %>
      <% end %>

      <% if policy(@tag).can_lock? %>
        <%= f.input :is_locked, :collection => [["No", "false"], ["Yes", "true"]], :include_blank => false %>
      <% end %>

      <%= f.button :submit, "Submit" %>
    <% end %>
  </div>
</div>

<%= render "secondary_links" %>

app/views/tags/index.html.erb
<% meta_description "Search thousands of tags on #{Danbooru.config.app_name}." %>

<div id="c-tags">
  <div id="a-index" class="fixed-width-container">
    <%= render "search" %>

    <%= table_for @tags, class: "striped autofit" do |t| %>
      <% t.column "Name", td: {class: "col-expand"} do |t| %>
        <%= link_to_wiki "?", t.name, class: tag_class(t) %>
        <%= link_to t.name, posts_path(tags: t.name), class: tag_class(t) %>

        <% tag_alias = t.tag_alias_for_pattern(params[:search][:name_or_alias_matches]) %>
        <% if tag_alias.present? %>
          ← <%= link_to tag_alias.antecedent_name, tag_alias, class: "fineprint" %>
        <% end %>

        <%= tag.span humanized_number(t.post_count), class: "post-count", title: t.post_count %>
      <% end %>
      <% t.column column: "control" do |tag| %>
        <% if policy(tag).update? %>
          <%= link_to "Edit", edit_tag_path(tag) %> |
        <% end %>
        <%= link_to "History", post_versions_path(search: { changed_tags: tag.name }) %> |
        <%= link_to "Related", related_tag_path(search: { query: tag.name }) %> |
        <%= link_to "Similar", tags_path(search: { fuzzy_name_matches: tag.name, order: :similarity }) %>
      <% end %>
    <% end %>

    <%= numbered_paginator(@tags) %>
  </div>
</div>

<%= render "secondary_links" %>

app/views/tags/index.sitemap.erb
<?xml version="1.0" encoding="UTF-8"?>

<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <% @tags.each do |tag| %>
    <url>
      <loc><%= posts_url(tags: tag.name) %></loc>
      <lastmod><%= tag.updated_at.iso8601 %></lastmod>
    </url>
  <% end %>
</urlset>

app/views/tags/show.html.erb
<% page_title "Tag: #{@tag.pretty_name.titleize}" %>
<%= render "secondary_links" %>

<div id="c-tags">
  <div id="a-show">
    <h1>Tag: <%= @tag.name %></h1>

    <ul>
      <li>Count: <%= @tag.post_count %></li>
      <li>Category: <%= @tag.category_name %></li>
    </ul>
  </div>
</div>